### ISSUE TITLE
Navigation Hover Issue

### ISSUE THREAD

**Issue by kieffer-reitenbach** [kieffer-reitenbach/web-design-2-independent-project#1]
@wendywarren

I'm trying to get a hover state on the logo, like we had talked about last week. Because it's not actually text I'm not sure how to do that. I played around with fill as well as filter but neither of those worked.

**Comment by wendywarren** [comment]
Hi Kieffer!

I took a look and here's a way you can handle the change of color when you hover your logo. 

First you'll want to include the svg directly in your html like this in order for you to manipulate in css. 

`<svg xmlns="http://www.w3.org/2000/svg" width="922.1" height="212.7" viewBox="0 0 922.1 212.7"><g><path d="M79.6 115.8l19.6 24.9v44h36.6V18.6H99.2v72.5L42.8 18.6H.7l53.5 68.1-54.2 98h41.8z"/><path d="M156 123.4h-19.8v61.3H99.6V18.6h67.9c40.8 0 57 15.3 57 52.5 0 27.1-8.8 42.7-29.6 48.9l35.9 64.7H189zm-19.8-31.3h27.4c17.8 0 24.2-6.1 24.2-21s-6.4-21.3-24.2-21.3h-27.4zM256.4 0h12.7v212.7h-12.7zm80.3 65.9h-8.6v26.9H312V20h29.8c17.9 0 24.9 6.7 24.9 23 0 11.9-3.8 18.7-12.9 21.4l15.7 28.4h-18.3zm-8.6-13.7h12c7.8 0 10.6-2.7 10.6-9.2s-2.8-9.3-10.6-9.3h-12zM430.8 79v13.8h-51V20h49.9v13.8h-33.8v15.1h28.4v13.7h-28.4V79zm11.8-59h16.1v72.8h-16.1zm79.8 14h-19.5v58.8h-16V34h-19.5V20h55zm59.7 45v13.8h-51V20H581v13.8h-33.9v15.1h28.5v13.7h-28.5V79zm68.8-59v72.8h-15.3l-26.5-49v49h-15.2V20H611l24.7 45.9V20zm16.1 0h29.2c17.1 0 24.6 5.9 24.6 18.9 0 8.1-2.9 13.1-9.9 15.6v.2c8.7 2.4 12.3 8.1 12.3 17.6 0 14.2-7.7 20.5-24.8 20.5H667zm26.7 29c8.5 0 11.3-1.9 11.3-7.8s-2.6-7.6-10.4-7.6H683V49zm2 30.2c8.5 0 11.4-2 11.4-8.1s-3.2-8.5-12.7-8.5H683v16.6zm75.1-1.1h-22.9l-4.6 14.7H727L751.4 20H768l24.5 72.8h-17.1zm-18.9-13.4h15l-7.5-26.5zm44.6-.2V48.3c0-20.3 9-29.6 28.3-29.6s27.4 8.7 27.8 27.5h-15.3c-.3-9.6-3.7-13.7-12.3-13.7s-12.4 4.5-12.4 16.1v15.6c0 11.6 3.4 16.1 12.4 16.1s12-4.1 12.3-13.6h15.3c-.4 18.7-9.2 27.4-27.8 27.4s-28.3-9.3-28.3-29.6zM922.1 20v72.8h-16V62.7H881v30.1h-16.1V20H881v28.8h25.1V20zM367.2 148.6V164c0 19.9-8.7 28.7-28.3 28.7h-27.1v-72.8h27.1c19.6 0 28.3 9 28.3 28.7zm-16.1.3c0-11.3-3.6-15.3-14.4-15.3h-8.8V179h8.8c10.8 0 14.4-3.9 14.4-15.3zm80.5 30v13.8h-51v-72.8h49.9v13.8h-33.9v15.1h28.5v13.7h-28.5v16.4zm7.5-8.1h15.7c0 7.1 3.9 10.2 11.8 10.2s10.6-2.6 10.6-7.8-3.9-8.6-14.7-10.3c-16.2-2.6-22.3-8.6-22.3-21.9 0-14.9 9.1-22.4 26.5-22.4s25.6 7.3 25.6 22.6h-15.7c0-6.3-3.3-9.5-10.2-9.5s-10.1 2.9-10.1 7.7 3.7 7.9 14 9.4c17 2.5 22.9 9 22.9 22.7s-8.9 22.5-27.1 22.5-27-7.2-27-23.2zm65.4-50.9h16v72.8h-16zm86.8 45.4c0 19.5-9.1 28.7-28.3 28.7s-29-9.5-29-29v-17.3c0-19.5 9.6-29.1 28.5-29.1s27.5 8.2 28.2 23.9h-15.3c-.6-6.7-4.3-10-12.5-10s-12.8 4.5-12.8 16v15.7c0 11.4 3.7 16 13.3 16S576 176 576 165.3h-12v-13.8h27.3zm70.2-45.4v72.8h-15.3l-26.4-49v49h-15.2v-72.8h17l24.7 46v-46z"/></g></svg>`

You have to remove the fill from the svg file before you include it so that you can adjust in the css.

In your css you will simply target the svg and there you can play around with width, fill, etc..

```
.banner-logo svg {
    fill: #fff;
}

.banner-logo svg:hover {
    fill: #f8b563;
}
```

Remember that it will display the width and height set in the svg properties. If you want that changed, can you change and export again from Illustrator or adjust width and height in css.

Here is some more info on ways you can include svg's in your site: https://learn-the-web.algonquindesign.ca/topics/svg-cheat-sheet/#setup

I hope that helps. Let me know if you have any questions.

Wendy

**Comment by wendywarren** [comment]
In class (week 6) we worked on adjusting fill color using sprite icons. For one off svg's like your logo it is perfectly fine to include directly in your html. When we get into icons, it's best to combine in a sprite.
